# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161026_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='\u0444\u043e\u0442\u043e \u043f\u0440\u043e\u0444\u0438\u043b\u044f'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='\u0438\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u0444\u0430\u043c\u0438\u043b\u0438\u044f'),
        ),
    ]
