# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20161016_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-pub_date',), 'verbose_name': '\u0424\u043e\u0442\u043e\u043a\u0430\u0440\u0442\u043e\u0447\u043a\u0430', 'verbose_name_plural': '\u0424\u043e\u0442\u043e\u043a\u0430\u0440\u0442\u043e\u0447\u043a\u0438'},
        ),
    ]
