# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(blank='True', choices=[('Life', 'life'), ('Nature', 'nature'), ('Culture', 'culture'), ('Sciense', 'science'), ('Space', 'space'), ('News', 'news'), ('Humor', 'humor'), ('Information Technology', 'IT')], max_length=1024),
        ),
    ]
