# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20161102_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug_field',
            field=models.SlugField(max_length=15, verbose_name='\u041e\u0431\u043e\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
    ]
