# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20161018_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='photo',
        ),
    ]
